# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pacCommand.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pacCommand.proto\x12\x13princetonGameEngine\"\xda\x01\n\nPacCommand\x12\x38\n\x07\x63ommand\x18\x01 \x02(\x0b\x32\'.princetonGameEngine.PacCommand.Command\x1a\x62\n\x07\x43ommand\x12<\n\tdirection\x18\x01 \x02(\x0e\x32).princetonGameEngine.PacCommand.Direction\x12\x19\n\x11\x66orwards_distance\x18\x02 \x02(\x05\".\n\tDirection\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x12\x0c\n\x08\x46ORWARDS\x10\x02')



_PACCOMMAND = DESCRIPTOR.message_types_by_name['PacCommand']
_PACCOMMAND_COMMAND = _PACCOMMAND.nested_types_by_name['Command']
_PACCOMMAND_DIRECTION = _PACCOMMAND.enum_types_by_name['Direction']
PacCommand = _reflection.GeneratedProtocolMessageType('PacCommand', (_message.Message,), {

  'Command' : _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
    'DESCRIPTOR' : _PACCOMMAND_COMMAND,
    '__module__' : 'pacCommand_pb2'
    # @@protoc_insertion_point(class_scope:princetonGameEngine.PacCommand.Command)
    })
  ,
  'DESCRIPTOR' : _PACCOMMAND,
  '__module__' : 'pacCommand_pb2'
  # @@protoc_insertion_point(class_scope:princetonGameEngine.PacCommand)
  })
_sym_db.RegisterMessage(PacCommand)
_sym_db.RegisterMessage(PacCommand.Command)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PACCOMMAND._serialized_start=42
  _PACCOMMAND._serialized_end=260
  _PACCOMMAND_COMMAND._serialized_start=114
  _PACCOMMAND_COMMAND._serialized_end=212
  _PACCOMMAND_DIRECTION._serialized_start=214
  _PACCOMMAND_DIRECTION._serialized_end=260
# @@protoc_insertion_point(module_scope)
