# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ack.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tack.proto\x12\x07\x62otCode\"\x15\n\x03\x41\x63k\x12\x0e\n\x06hasAck\x18\x01 \x02(\x05')



_ACK = DESCRIPTOR.message_types_by_name['Ack']
Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'ack_pb2'
  # @@protoc_insertion_point(class_scope:botCode.Ack)
  })
_sym_db.RegisterMessage(Ack)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACK._serialized_start=22
  _ACK._serialized_end=43
# @@protoc_insertion_point(module_scope)
