# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightState.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10lightState.proto\x12\x07\x62otCode\"\xf9\x03\n\nLightState\x12.\n\x06pacman\x18\x01 \x02(\x0b\x32\x1e.botCode.LightState.AgentState\x12\x31\n\tred_ghost\x18\x02 \x02(\x0b\x32\x1e.botCode.LightState.AgentState\x12\x32\n\npink_ghost\x18\x03 \x02(\x0b\x32\x1e.botCode.LightState.AgentState\x12\x34\n\x0corange_ghost\x18\x04 \x02(\x0b\x32\x1e.botCode.LightState.AgentState\x12\x32\n\nblue_ghost\x18\x05 \x02(\x0b\x32\x1e.botCode.LightState.AgentState\x12*\n\x04mode\x18\x06 \x02(\x0e\x32\x1c.botCode.LightState.GameMode\x12\r\n\x05score\x18\x08 \x02(\x05\x12\r\n\x05lives\x18\x0b \x02(\x05\x1aQ\n\nAgentState\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12-\n\x05state\x18\x04 \x01(\x0e\x32\x1e.botCode.LightState.GhostState\"#\n\x08GameMode\x12\x0b\n\x07RUNNING\x10\x00\x12\n\n\x06PAUSED\x10\x01\"(\n\nGhostState\x12\n\n\x06NORMAL\x10\x00\x12\x0e\n\nFRIGHTENED\x10\x01')



_LIGHTSTATE = DESCRIPTOR.message_types_by_name['LightState']
_LIGHTSTATE_AGENTSTATE = _LIGHTSTATE.nested_types_by_name['AgentState']
_LIGHTSTATE_GAMEMODE = _LIGHTSTATE.enum_types_by_name['GameMode']
_LIGHTSTATE_GHOSTSTATE = _LIGHTSTATE.enum_types_by_name['GhostState']
LightState = _reflection.GeneratedProtocolMessageType('LightState', (_message.Message,), {

  'AgentState' : _reflection.GeneratedProtocolMessageType('AgentState', (_message.Message,), {
    'DESCRIPTOR' : _LIGHTSTATE_AGENTSTATE,
    '__module__' : 'lightState_pb2'
    # @@protoc_insertion_point(class_scope:botCode.LightState.AgentState)
    })
  ,
  'DESCRIPTOR' : _LIGHTSTATE,
  '__module__' : 'lightState_pb2'
  # @@protoc_insertion_point(class_scope:botCode.LightState)
  })
_sym_db.RegisterMessage(LightState)
_sym_db.RegisterMessage(LightState.AgentState)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIGHTSTATE._serialized_start=30
  _LIGHTSTATE._serialized_end=535
  _LIGHTSTATE_AGENTSTATE._serialized_start=375
  _LIGHTSTATE_AGENTSTATE._serialized_end=456
  _LIGHTSTATE_GAMEMODE._serialized_start=458
  _LIGHTSTATE_GAMEMODE._serialized_end=493
  _LIGHTSTATE_GHOSTSTATE._serialized_start=495
  _LIGHTSTATE_GHOSTSTATE._serialized_end=535
# @@protoc_insertion_point(module_scope)
